################################################################################
# These macros are used by makefiles and argument files.
# When a space is included in the path and quotes (") cannot be used,
# a _ESCAPE version of the macro is added that escapes the space with backslash (\).
################################################################################

export BUILD_11_RFTPMS_FLASH=C:/Users/admin/Downloads/build-11.RfTPMS-FLASH
export HC08ToolsEnv=$(CWInstallLocationEnv)/MCU/prog
export GNU_Make_Install_DirEnv=$(CWInstallLocationEnv)/gnu/bin
export ProjDirPath=C:/Users/admin/workspace/11.RfTPMS
export CWInstallLocationEnv=C:/Freescale/CW MCU v11.1
export MCUToolsBaseDirEnv=$(CWInstallLocationEnv)/MCU
export LIB=C:/Users/admin/Downloads/build-11.RfTPMS-FLASH/Lib
export SOURCES=C:/Users/admin/workspace/11.RfTPMS/Sources
export STARTUP_CODE=C:/Users/admin/Downloads/build-11.RfTPMS-FLASH/Project_Settings/Startup_Code
export SOURCES1=C:/Users/admin/Downloads/build-11.RfTPMS-FLASH/Sources
